### ISSUE TITLE
Pre-trained Model(s)

### ISSUE THREAD

**Issue by javi-99** [Halmstad-University/TITAN-NET#2]
Hi,
Thank you for your good work, I want to replicate your work, but while trying to train TITAN-Net, we discovered that we need to run and create output from other networks in the pipeline before training TITAN-Net.  if possible can you provide the pre-trained model of your whole pipeline containing SD-Net, SalsaNext, TITAN-Next, and vid2vid as mentioned in your paper.  Thanks

**Comment by TiagoCortinhal** [comment]
Hello!

Titan-net : https://drive.google.com/file/d/1ypwqJEgwG90ATvbnw9zAubb6A-xZ8Zeh/view?usp=sharing
SD-Net (from https://github.com/NVIDIA/semantic-segmentation): https://drive.google.com/file/d/1TLys-tZpqPrLXx7s8SImKgZy9wmtdsZY/view?usp=drive_link
SalsaNext (from https://github.com/TiagoCortinhal/SalsaNext): https://drive.google.com/file/d/1TbuF4EfLN1eoE2xtEAr_JzDqrtsOjGMp/view
Vid2Vid (from https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix): https://drive.google.com/file/d/1hWV1rL9sKQJXsV7hPbLxHa8gSmyuMOky/view?usp=drive_link
Titan-Next (from https://github.com/TiagoCortinhal/TITAN-Next ): https://drive.google.com/file/d/1fEKd9jHOV39smMATNm8x_EWH8L9QMSox/view?usp=drive_link

**Comment by javi-99** [comment]
Thank you for sharing, I can access all pre-trained models.

**Comment by michael861227** [comment]
Hello,

Thank you for your excellent work. I'm interested in replicating your results using a pretrained model. However, I noticed that the pretrained weights for Vid2Vid on the GitHub repository are from https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix instead of https://github.com/NVIDIA/vid2vid.

Therefore, I want to know which github repo is your Vid2Vid pretrained model use for.
Thanks

**Comment by ten10second** [comment]
Hello,

The link to the Vid2Vid pre-trained model you provided does not exist.
Vid2Vid (from https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix): https://drive.google.com/file/d/1hWV1rL9sKQJXsV7hPbLxHa8gSmyuMOky/view?usp=drive_link
